### ISSUE TITLE
can you give steps on how run notabilitytohtml.py 

### ISSUE THREAD

**Issue by kaolagithub** [tacocats/notability-converter#1]
I'm new to python.I just basicly know how to run .py script,not work well.Can you give steps on how run notabilitytohtml.py well
Here below is debug information.
metadata.plist
Traceback (most recent call last):
  File "C:\run\notabilitytohtml.py", line 82, in <module>
    test()
  File "C:\run\notabilitytohtml.py", line 77, in test
    r.readFile("test.note")
  File "C:\run\notabilitytohtml.py", line 22, in readFile
    self.decodePlistFiles(self.directory)
  File "C:\run\notabilitytohtml.py", line 47, in decodePlistFiles
    pl = plistlib.readPlist((os.path.join(d, subdir, f).replace("\\", "\\\\")))
AttributeError: module 'plistlib' has no attribute 'readPlist'
>>>

**Comment by tacocats** [comment]
Hey, sorry my github inbox is a mess and I haven't touched this project in a while. 

The error is due to the python library being changed. I'm going to be pushing some changes in the next week to have a basic export working again.
